#include "vole_params.h"

#if defined(PRG_AES_CTR)
EXTERN_DEFINE_PRG_AES_CTR(vole)
#elif defined(PRG_RIJNDAEL_EVEN_MANSOUR)
EXTERN_DEFINE_PRG_RIJNDAEL_FIXED_KEY_CTR(vole)
#endif

#if defined(TREE_PRG_AES_CTR)
EXTERN_DEFINE_PRG_AES_CTR(tree)
#elif defined(TREE_PRG_RIJNDAEL_EVEN_MANSOUR)
EXTERN_DEFINE_PRG_RIJNDAEL_FIXED_KEY_CTR(tree)
#endif

#if defined(LEAF_PRG_AES_CTR)
EXTERN_DEFINE_PRG_AES_CTR(leaf)
#elif defined(LEAF_PRG_RIJNDAEL_EVEN_MANSOUR)
EXTERN_DEFINE_PRG_RIJNDAEL_FIXED_KEY_CTR(leaf)
#endif
